// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGoZrLQalRqU3A7hOo5LOImb3394HxtLo',
    appId: '1:624201421340:web:b6cfca25de3905d5f8c5d9',
    messagingSenderId: '624201421340',
    projectId: 'klontong-apps-cf7c2',
    authDomain: 'klontong-apps-cf7c2.firebaseapp.com',
    storageBucket: 'klontong-apps-cf7c2.firebasestorage.app',
    measurementId: 'G-PT30WTYSQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnEYIVGKTBf9pyv3Ve9B6698FA0gFiZgE',
    appId: '1:624201421340:android:4b7e153835a42210f8c5d9',
    messagingSenderId: '624201421340',
    projectId: 'klontong-apps-cf7c2',
    storageBucket: 'klontong-apps-cf7c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBwOKXvYTGJAB4llNTh6gZ3E9_r0KUgg',
    appId: '1:624201421340:ios:06a40084a4f0af01f8c5d9',
    messagingSenderId: '624201421340',
    projectId: 'klontong-apps-cf7c2',
    storageBucket: 'klontong-apps-cf7c2.firebasestorage.app',
    iosBundleId: 'com.example.kelontongApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACBwOKXvYTGJAB4llNTh6gZ3E9_r0KUgg',
    appId: '1:624201421340:ios:06a40084a4f0af01f8c5d9',
    messagingSenderId: '624201421340',
    projectId: 'klontong-apps-cf7c2',
    storageBucket: 'klontong-apps-cf7c2.firebasestorage.app',
    iosBundleId: 'com.example.kelontongApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGoZrLQalRqU3A7hOo5LOImb3394HxtLo',
    appId: '1:624201421340:web:d00d2ef3bbd1c5f3f8c5d9',
    messagingSenderId: '624201421340',
    projectId: 'klontong-apps-cf7c2',
    authDomain: 'klontong-apps-cf7c2.firebaseapp.com',
    storageBucket: 'klontong-apps-cf7c2.firebasestorage.app',
    measurementId: 'G-XWTWR3SJLB',
  );
}
